### PR TITLE
Flatpak 1.14.4

### LINKED ISSUE #5434: [Bug]: F: Failed to parse /var/lib/flatpak/appstream/gnome/x86_64/active/appstream.xml.gz file: Error on line 1906 char 29: <p> already set '
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04.2 LTS

### What architecture are you using?

x86_64

### How to reproduce

Search for packages:

`flatpak search firefox`

### Expected Behavior

Output of the package found or not found

### Actual Behavior

```bash
flatpak search firefox
F: Failed to parse /var/lib/flatpak/appstream/gnome/x86_64/active/appstream.xml.gz file: Error on line 1906 char 29: <p> already set '
      Organic Maps is a free Android & iOS offline maps app for travelers,
      tourists, hikers, and cyclists.
      It uses crowd-sourced OpenStreetMap data and is developed with love by
      ' and tried to replace with ' ('
No matches found
```

### Additional Information

**Line 1906**:

```html
      <em>MapsWithMe</em> (<em>MapsMe</em>) founders and our community.
```

Lines surrounding line 1906:
```html
      <p>
      Organic Maps is a free Android &amp; iOS offline maps app for travelers,
      tourists, hikers, and cyclists.
      It uses crowd-sourced OpenStreetMap data and is developed with love by
      <em>MapsWithMe</em> (<em>MapsMe</em>) founders and our community.
      No ads, no tracking, no data collection, no crapware.
      Your donations and positive reviews motivate and inspire us, thanks ❤️!
    </p>

```

### PR DESCRIPTION
**Pull request by 13r0ck**
Should fix https://github.com/flatpak/flatpak/issues/5434

This branch will be pushed to `master_jammy` when approved. Please ignore the merge branch of `master_focal` here

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Review by n3m0-22 — APPROVED** [review]
This has fixed the issue. It does however lead to another issue.

When running `flatpak search ...` you get flooded with lines of 
`GLib-CRITICAL **: 21:47:15.139: g_once_init_leave: assertion 'g_atomic_pointer_get (value_location) == 0' failed`

After that you get the search results as expected.

This should not hold up this PR though as this does get flatpak working again, but appstream will need to be updated as well.

**Comment by ximion** [comment]
> This has fixed the issue. It does however lead to another issue.

You would need to update `appstream` as well - to `0.15.4` or higher (so http://archive.ubuntu.com/ubuntu/pool/main/a/appstream/appstream_0.15.5-1.dsc would work). Or wait for Ubuntu to resolve this as SRU.

**Comment by 13r0ck** [comment]
@n3m0-22 can you please check that https://github.com/pop-os/appstream fixes the appstream issue?

(Thank you @ximion! )

**Comment by n3m0-22** [comment]
> @n3m0-22 can you please check that https://github.com/pop-os/appstream fixes the appstream issue?
> 
I tested and it does resolve the issue on my end.

**Comment by n3m0-22** [comment]
The rebase of appstream https://github.com/pop-os/appstream is now working correctly. I was able to build it without issue. Running `ninja test` shows all tests as passing. After installing the remaining issue of `GLib-CRITICAL **` flooding the terminal when running `flatpak search ...` is resolved.

**Comment by 13r0ck** [comment]
Merged into master jammy

**Pull request closed without merging**
